[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
backgroundColor = "#0d0e14"
secondaryBackgroundColor = "#111219"
textColor = "#e8e9f0"
font = "sans serif"
